In [16]:
import os
import sys
%cd ~/erc-src/cuneiform-ocr/
os.getcwd()

module_path = os.path.abspath('./mmdetection')
sys.path.insert(0, module_path)

%load_ext autoreload
%autoreload 2

import mmdet
import mmengine
print(f"MMDetection version: {mmdet.__version__}")
print(f"MMEngine version: {mmengine.__version__}")

from mmdet.apis import init_detector, inference_detector
from mmdet.utils import register_all_modules
from mmdet.registry import VISUALIZERS
import mmcv
from pymongo import MongoClient
from dotenv import load_dotenv


load_dotenv()
MONGODB_URI = os.getenv("MONGODB_URI")
if not MONGODB_URI:
    raise ValueError("MONGODB_URI is not set")

/home/jebediahc/erc-src/cuneiform-ocr
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
MMDetection version: 3.0.0
MMEngine version: 0.10.7


In [17]:
config_file = 'configs/detr.py'
# config_file = '/dss/dsshome1/02/di97tod/erc-work-data/old_models/detr-2024/detr.py'

checkpoint_file = '~/erc-work-data/retrained_models/detr-173/epoch_1000.pth'
# checkpoint_file = '~/erc-work-data/retrained_models/detr-106/epoch_960.pth'
# checkpoint_file = '~/erc-src/cuneiform-ocr/mmdetection/work_dirs/deformable-detr-refine-twostage_r50_16xb2-50e_coco/epoch_320.pth'

In [18]:
#Register all modules in mmdet into the registries
register_all_modules()
# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')  # or device='cpu'


Loads checkpoint by local backend from path: ~/erc-work-data/retrained_models/detr-173/epoch_1000.pth


In [19]:
from data_processing.divide_photos import divide_tablet_photo

# Divide the tablet photo into fragments
cropped_images = divide_tablet_photo(
    'imgs/HS.2086.jpg',
    # visualize=True # Generate visualization result
    visualize=False,
    output_path="visualizations/generated_devision_result.jpg",
)

# cropped_images is a list, each element is an image (numpy array)
# Already sorted from top to bottom, left to right
for i, cropped_img in enumerate(cropped_images):
    print(f"Fragment {i+1}: {cropped_img.shape}")
    center_y, center_x = cropped_img.shape[0] // 2, cropped_img.shape[1] // 2
    patch = cropped_img[center_y-1:center_y+2, center_x-1:center_x+2]
    print(f"Center 3x3 patch of fragment {i + 1}:\n", patch)


before: 20 boxes, merge threshold: 5.0 pixels
after nearby merge: 20 boxes
after overlap merge: 20 boxes
after keeping top 12 largest: 12 boxes
after removing small boxes: 8 boxes
Fragment 1: (2840, 752, 3)
Center 3x3 patch of fragment 1:
 [[[ 88 131 188]
  [ 93 136 193]
  [ 94 137 194]]

 [[ 90 133 190]
  [ 94 137 194]
  [ 95 138 195]]

 [[ 92 135 192]
  [ 96 139 196]
  [ 96 139 196]]]
Fragment 2: (2835, 1262, 3)
Center 3x3 patch of fragment 2:
 [[[114 151 203]
  [120 157 209]
  [119 154 204]]

 [[130 168 222]
  [130 169 221]
  [127 164 214]]

 [[130 168 222]
  [128 167 219]
  [121 158 210]]]
Fragment 3: (2841, 742, 3)
Center 3x3 patch of fragment 3:
 [[[ 49  96 158]
  [ 50  97 159]
  [ 55  99 162]]

 [[ 41  85 148]
  [ 42  86 149]
  [ 46  90 153]]

 [[ 42  86 149]
  [ 43  87 150]
  [ 50  94 157]]]
Fragment 4: (728, 1273, 3)
Center 3x3 patch of fragment 4:
 [[[ 68 106 160]
  [ 68 106 160]
  [ 80 117 169]]

 [[ 84 124 177]
  [ 82 122 175]
  [ 86 124 178]]

 [[ 93 133 186]
  [ 91 131 18

In [20]:
# test one or more images
# img = mmcv.imread('imgs/K.2.jpg', channel_order='rgb')
import cv2

imgs = cropped_images
inference_results = []
for i, img in enumerate(imgs):
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
    result = inference_detector(model, img)
    inference_results.append(result)
    print(f"Result for image {i}: {result}")

Result for image 0: <DetDataSample(

    META INFORMATION
    img_shape: (1333, 353)
    img_id: 0
    img_path: None
    batch_input_shape: (1333, 353)
    pad_shape: (1333, 353)
    scale_factor: (0.46941489361702127, 0.4693661971830986)
    ori_shape: (2840, 752)

    DATA FIELDS
    pred_instances: <InstanceData(
        
            META INFORMATION
        
            DATA FIELDS
            bboxes: tensor([[ 153.5602, 1682.0283,  325.6491, 1813.1722],
                        [ 153.5602, 1682.0283,  325.6491, 1813.1722],
                        [ 327.7888, 2647.2104,  436.3369, 2727.8022],
                        [ 282.3791, 2421.7861,  375.3639, 2535.3877],
                        [ 239.3136,  820.1111,  305.6328,  928.7002],
                        [ 288.5570, 2640.9243,  440.5373, 2733.7009],
                        [ 282.3791, 2421.7861,  375.3639, 2535.3877],
                        [ 148.4003, 1495.6953,  302.7546, 1626.5858],
                        [ 331.3117, 2646.2949,

In [21]:
# init the visualizer(execute this block only once)
visualizer = VISUALIZERS.build(model.cfg.visualizer)
# the dataset_meta is loaded from the checkpoint and
# then pass to the model in init_detector
visualizer.dataset_meta = model.dataset_meta

/home/jebediahc/anaconda3/envs/cuneiform-ocr/lib/python3.10/site-packages/mmengine/utils/manager.py:113: UserWarning: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not accept any other arguments
  warnings.warn(


In [22]:
print(len(model.dataset_meta["classes"]))
print(model.dataset_meta["classes"])

173
['TU', '|U.GUD|', 'TUM', 'LA', 'TA', 'GAR', 'GAL', 'I', 'TI', 'LI', 'ZA', 'A', 'DI', 'MI', 'RI', 'IŠ', 'BA', 'LU', 'TE', 'DA', '|GUD×KUR|', 'MA', 'E₂', 'DIŠ', 'MU', 'DU', 'ŠU₂', 'EN', 'KUL', 'SI', '|I.A|', 'HI', 'MUŠ₃', 'AN', 'NA', 'BAD', 'AMAR', 'UD', 'UnclearSign', '|HI×BAD|', '|UD×(U.U.U)|', 'AB', 'AK', 'LUGAL', 'DIN', 'KI', 'DUN₃@g', 'KU₃', 'AŠ', 'IGI', 'U₂', 'ŠA₃', 'BI', 'GUR', 'ŠE', 'ZI', 'GA', 'SILA₃', 'ŠID', '|SAL.TUG₂|', 'SU', 'KAK', 'MAŠ', 'TUR', 'ŠEŠ', 'LU₂', 'IA₂', 'UR', 'KAL', '|ŠEŠ.KI|', 'ZU', 'ŠU', 'NE', 'IM', 'RA', '|U.U|', 'ZAG', '|DIŠ.DIŠ.DIŠ|', 'GA₂', 'IN', 'KIN', 'TAR', 'MAH', 'LAL', 'KID', 'GABA', 'KA', 'RU', 'ŠA', '|HI×NUN|', 'ME', 'BU', 'NI', 'IG', 'MES', 'PA', 'SAG', 'U', 'E', 'GUM', 'GIŠ', '|U.KA|', 'LUM', '|HI×AŠ₂|', 'HA', 'UŠ', '|U.U.U|', 'MIN', 'NAM', 'NU', 'AL', 'AB₂', 'IB', 'UM', 'KU', 'SUR', 'MEŠ', 'TUG₂', 'TAG', 'DIM', 'BAL', 'IR', 'ERIN₂', 'PAP', 'SA', '|PIRIG×ZA|', 'UB', 'URU', '|U.5(DIŠ)|', 'DAM', 'GAR₃', '|EN.ZU|', 'ZE₂', 'AD', 'APIN', 'EL', 'PI'

In [23]:
# classes = ['TU', '|U.GUD|', 'TUM', 'LA', 'TA', 'GAR', 'GAL', 'I', 'TI', 'LI', 'ZA', 'A', 'DI', 'MI', 'RI', 'IŠ', 'BA', 'LU', 'TE', 'DA', '|GUD×KUR|', 'MA', 'E₂', 'DIŠ', 'MU', 'DU', 'ŠU₂', 'EN', 'KUL', 'SI', '|I.A|', 'HI', 'MUŠ₃', 'AN', 'NA', 'BAD', 'AMAR', 'UD', 'UnclearSign', '|HI×BAD|', '|UD×(U.U.U)|', 'AB', 'AK', 'LUGAL', 'DIN', 'KI', 'DUN₃@g', 'KU₃', 'AŠ', 'IGI', 'U₂', 'ŠA₃', 'BI', 'GUR', 'ŠE', 'ZI', 'GA', 'SILA₃', 'ŠID', '|SAL.TUG₂|', 'SU', 'KAK', 'MAŠ', 'TUR', 'ŠEŠ', 'LU₂', 'IA₂', 'UR', 'KAL', '|ŠEŠ.KI|', 'ZU', 'ŠU', 'NE', 'IM', 'RA', '|U.U|', 'ZAG', '|DIŠ.DIŠ.DIŠ|', 'GA₂', 'IN', 'KIN', 'TAR', 'MAH', 'LAL', 'KID', 'GABA', 'KA', 'RU', 'ŠA', '|HI×NUN|', 'ME', 'BU', 'NI', 'IG', 'MES', 'PA', 'SAG', 'U', 'E', 'GUM', 'GIŠ', '|U.KA|', 'LUM', '|HI×AŠ₂|', 'HA', 'UŠ', '|U.U.U|', 'MIN', 'NAM', 'NU', 'AL', 'AB₂', 'IB', 'UM', 'KU', 'SUR', 'MEŠ', 'TUG₂', 'TAG', 'DIM', 'BAL', 'IR', 'ERIN₂', 'PAP', 'SA', '|PIRIG×ZA|', 'UB', 'URU', '|U.5(DIŠ)|', 'DAM', 'GAR₃', '|EN.ZU|', 'ZE₂', 'AD', 'APIN', 'EL', 'PI', 'AŠ@z', 'DAR', 'DUB', 'SAR', 'GUD', 'A₂', 'KUR', 'ARAD', '|IGI.DIB|', '6(DIŠ)', 'AŠ₂', 'IL', 'HU', 'NUN', 'SAL', 'GI', 'EŠ₂', 'UN', 'TIL', 'NIM', 'TAB', 'SUM', '|3×AN|', '|NINDA₂׊E|', 'MAŠ₂', 'GI₄', 'GAN', 'DIM₂', 'GU', 'MAR', 'MUŠ', 'BAR', '|IGI.RI|', 'TUK', '|UD.DU|', '|LAGAB.LAGAB|']

# print(len(classes))
# print(classes.index('UnclearSign'), classes.index("DU"))

# classes_106 = classes[:106]

In [24]:
import random


print(f"Palette length: {len(model.dataset_meta['palette'])}")
def extend_rgb_list(rgb_list, target_length):
    """
    Extends the given list of RGB tuples to the target length by adding unique RGB tuples.
    """

    # Set for faster lookup of existing tuples
    existing_colors = set(rgb_list)

    # Add unique tuples until the list reaches the target length
    while len(rgb_list) < target_length:
        new_color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

        if new_color not in existing_colors:
            rgb_list.append(new_color)
            existing_colors.add(new_color)

    return rgb_list

model.dataset_meta["palette"] = extend_rgb_list(model.dataset_meta["palette"], len(model.dataset_meta["classes"]))
print(f"Extended palette length: {len(model.dataset_meta['palette'])}")

Palette length: 106
Extended palette length: 173


In [ ]:
# show the results
import matplotlib.pyplot as plt

imgs_to_visualize = imgs  # List of images

for idx, (img, result) in enumerate(zip(imgs_to_visualize, inference_results)):
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
    visualizer.add_datasample(
        f'result_{idx}',
        img,
        data_sample=result,
        draw_gt=False,
        wait_time=0,
    )

    drawn_img = visualizer.get_image()

    plt.figure(figsize=(10, 8))
    plt.imshow(drawn_img)
    plt.title(f'Cropped {idx + 1}')
    plt.axis('off')
    plt.show()


In [26]:
classes = model.dataset_meta['classes']

In [27]:
from data_processing.line_process import line_signs
import numpy as np

THRESHOLD_CERTAIN = 0.7


line_signs_results = []
for img, result in zip(imgs, inference_results):
    OCR_result = result.pred_instances.cpu()
    labels, bboxes = OCR_result['labels'], OCR_result['bboxes']

    certain_scores_idx = len(OCR_result["scores"][OCR_result["scores"] > THRESHOLD_CERTAIN])
    certain_bboxes = bboxes[:certain_scores_idx]
    labels = OCR_result['labels'][:certain_scores_idx]
    scores = OCR_result['scores'][:certain_scores_idx]  # to debug
    
    lined_signs = line_signs(
        certain_bboxes, labels, classes,
        eps=0.4,
        min_samples=1,
        lambda_weight=0.007)  # scores to debug
    print("Recognized text:\n", lined_signs)
    line_signs_results.append(lined_signs)


Recognized text:
 
Recognized text:
 DIŠ LU 
GAR 
TUM RI 
DIŠ ZE₂ NI AN |SAL.TUG₂| IB AN UD 
DIŠ DAR MI BA AN 
DIŠ KA UM AN UD TUR 
UnclearSign 
DIŠ E₂ A E RI BA 
EŠ₂ MU UN NA AN 
BI BU RU UM KID 
KI LU₂ 
A 
|IGI.DIB| 
TUR LUGAL MU NA |U.U.U| 
|IGI.DIB| DI E 
BI IN KU BI |U.U.U| 
MI SAG GU BA 
DIŠ 
TUR AN UD GA IŠ 
NE IN E |U.U.U| 
MU DAR UM 
BI KA 
E 
DIŠ DAR UM MI |IGI.DIB| 
E NE |IGI.DIB| BU 
DIŠ BA UnclearSign AN |SAL.TUG₂| IB 
KA 
SUM MU DA |IGI.DIB| 
DAR UM 

Recognized text:
 |U.U.U| 
DA NE 
NA 
NUN BA 
DUN₃@g 
AN |SAL.TUG₂| 
A 
TUM 
DA NI 

Recognized text:
 
Recognized text:
 
Recognized text:
 GAR RI 
IM MI IN 
NE TA DIŠ 
|IGI.DIB| ARAD GABA ŠU RU BA BA TUM UnclearSign 
ŠA AN 
DIŠ NI KA 
DIŠ TUM TUR KI |IGI.DIB| TUR 
A BI DAR MI |IGI.DIB| 
A KID 
IGI NI AN NI I |IGI.DIB| IB ŠA GA AN |GUD×KUR| IŠ UD TUR TUR |EN.ZU| 
UnclearSign BI TUR U 
AN LU₂ TI LA TA 
UŠ PA 
ARAD UnclearSign 
UnclearSign 
AN PA 
IGI IGI ŠA TUR IR A ZE₂ DIM TUR IB ŠEŠ A GA NI 
IGI NU RU UM TUR NA MA AN 
IGI 

In [28]:
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient(MONGODB_URI)  
db = client['ebl']  
collection = db['signs']  

def get_abz_number(sign):
    if sign == "UnclearSign":
        return "X" 
    result = collection.find_one({"_id": sign})
    if result:
        for entry in result['lists']:
            if entry['name'] == 'ABZ':
                return 'ABZ' + entry['number']
    print(f"ABZ number not found for sign: {sign}")
    return 'X'  

# Convert signs to ABZ format
ABZ_result = []
for result in line_signs_results:
    for line in result.strip().split('\n'):
        line = line.split(' ')
        for idx, sign in enumerate(line):
            if len(sign) > 0:
                line[idx] = get_abz_number(sign)
        ABZ_result.append(line)

# Output the result
for line in ABZ_result:
    print(' '.join(line))

ABZ number not found for sign: |EN.ZU|

ABZ480 ABZ537 
ABZ597 
ABZ207 ABZ86 
ABZ480 ABZ147 ABZ231 ABZ13 ABZ556 ABZ535 ABZ13 ABZ381 
ABZ480 ABZ114 ABZ427 ABZ5 ABZ13 
ABZ480 ABZ15 ABZ134 ABZ13 ABZ381 ABZ144 
X 
ABZ480 ABZ324 ABZ579 ABZ308 ABZ86 ABZ5 
ABZ536 ABZ61 ABZ312 ABZ70 ABZ13 
ABZ214 ABZ371 ABZ68 ABZ134 ABZ313 
ABZ461 ABZ330 
ABZ579 
ABZ455 
ABZ144 ABZ151 ABZ61 ABZ70 ABZ472 
ABZ455 ABZ457 ABZ308 
ABZ214 ABZ148 ABZ536 ABZ214 ABZ472 
ABZ427 ABZ115 ABZ559 ABZ5 
ABZ480 
ABZ144 ABZ13 ABZ381 ABZ319 ABZ212 
ABZ172 ABZ148 ABZ308 ABZ472 
ABZ61 ABZ114 ABZ134 
ABZ214 ABZ15 
ABZ308 
ABZ480 ABZ114 ABZ134 ABZ427 ABZ455 
ABZ308 ABZ172 ABZ455 ABZ371 
ABZ480 ABZ5 X ABZ13 ABZ556 ABZ535 
ABZ15 
ABZ164 ABZ61 ABZ335 ABZ455 
ABZ114 ABZ134
ABZ472 
ABZ335 ABZ172 
ABZ70 
ABZ87 ABZ5 
ABZ595 
ABZ13 ABZ556 
ABZ579 
ABZ207 
ABZ335 ABZ231


ABZ597 ABZ86 
ABZ399 ABZ427 ABZ148 
ABZ172 ABZ139 ABZ480 
ABZ455 ABZ50 ABZ167 ABZ354 ABZ68 ABZ5 ABZ5 ABZ207 X 
ABZ353 ABZ13 
ABZ480 ABZ231 ABZ15 
ABZ480 ABZ207 ABZ144 ABZ461

In [29]:
classes_abz = []
classes_abz_dict = {}
for sign in model.dataset_meta["classes"]:
    abz_number = get_abz_number(sign)
    classes_abz.append(abz_number)
    classes_abz_dict[sign] = abz_number
print(classes_abz)
print(classes_abz_dict)
# search keys whose abz number is None
for sign, abz in classes_abz_dict.items():
    if abz is None:
        print(sign)

ABZ number not found for sign: |ŠEŠ.KI|
ABZ number not found for sign: |EN.ZU|
ABZ number not found for sign: |NINDA₂׊E|
ABZ number not found for sign: |UD.DU|
['ABZ58', 'ABZ441', 'ABZ207', 'ABZ55', 'ABZ139', 'ABZ597', 'ABZ343', 'ABZ142', 'ABZ73', 'ABZ59', 'ABZ586', 'ABZ579', 'ABZ457', 'ABZ427', 'ABZ86', 'ABZ212', 'ABZ5', 'ABZ537', 'ABZ376', 'ABZ335', 'ABZ170', 'ABZ342', 'ABZ324', 'ABZ480', 'ABZ61', 'ABZ206', 'ABZ545', 'ABZ99', 'ABZ72', 'ABZ112', 'ABZ142a', 'ABZ396', 'ABZ103', 'ABZ13', 'ABZ70', 'ABZ69', 'ABZ437', 'ABZ381', 'X', 'ABZ279', 'ABZ52', 'ABZ128', 'ABZ97', 'ABZ151', 'ABZ465', 'ABZ461', 'ABZ595', 'ABZ468', 'ABZ1', 'ABZ449', 'ABZ318', 'ABZ384', 'ABZ214', 'ABZ111', 'ABZ367', 'ABZ84', 'ABZ319', 'ABZ62', 'ABZ314', 'ABZ556', 'ABZ7', 'ABZ230', 'ABZ74', 'ABZ144', 'ABZ331', 'ABZ330', 'ABZ598a', 'ABZ575', 'ABZ322', 'X', 'ABZ6', 'ABZ354', 'ABZ172', 'ABZ399', 'ABZ328', 'ABZ471', 'ABZ332', 'ABZ593', 'ABZ233', 'ABZ148', 'ABZ538', 'ABZ12', 'ABZ57', 'ABZ481', 'ABZ313', 'ABZ167', 'ABZ15', 'AB